dist: trusty
sudo: false
language: ruby
rvm:
- 2.5.1
env:
- JEKYLL_ENV=production
script:
- "./scripts/build.sh"
deploy:
  provider: pages
  local-dir: _site
  skip-cleanup: true
  target-branch: gh-pages
  github-token: "$GITHUB_TOKEN"
  on:
    branch: master
notifications:
  on_success: change
  on_failure: always
  email: false
  slack:
    secure: Y9TfNGhj2qnzspu2FkWeT7D3Ra4v4rmzGlz1h+g2aNWcQ1Q4WzYXHOpV7nhbeK/2J3ec2/dkBmF5hz0LXvkg5HANE7MsZbKze9LbRc5JcglVfzUfv0spi9QDKbBs//KULD4vDxgwlu8aQzcD7jY2HNYbChEsatOBC1l9fUt4aRIQ9wQEmxvID5EphUm+R4di/DbHHFSpExbb9w21QAysYo5wgKaaqGd54gcKijftuN+m3RwhWhzQUE7foVCeBjHL41hM00oXqFkBmnrc7fQYFCkIEcCcblefdml2dvonbYE3MShRakDVqR/NtfF/ZKspHyzBaFyVIzPOZV5kQC4OXrgeyzawf2gR5TlPRe4nT82izxfaheKkE1mYJYraDmYVc8lbULqd/vaWJu8ifBf0saXKw3TzKl7dZSsKCo717lOFbqE9gQDeHyuRSl+muJRAOBtYarzVHYOOl4B8SUYStQ5uHxs2Y6GqyN+Mr5D7Frs0Awfkwt826UrnDolhDBVy3ldfF9HI2TpjeYcLGCgSx66lokelKLsYR4nac9bbQWZaJUy3hqPGzDuXa+uzH3ROewI6dVfoejyExcYYlw0Piy5PgcoyzcdReaW976gPUCEoNPGKKUDeUg8mioXns9fQmi7Ysd+haP2lHoKDqZsIgMa6W4tawI5G8fEBvSuZryc=
