dist: trusty
sudo: false
language: ruby
rvm:
- 2.5.1
env:
- JEKYLL_ENV=production
script:
- "./scripts/build.sh"
deploy:
  provider: pages
  local-dir: _site
  skip-cleanup: true
  target-branch: gh-pages
  github-token: "$GITHUB_TOKEN"
  on:
    branch: master
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: HGg8SpHznWpKW86uzFbuJuZB90K8Epy9GWCFlkWNup1yA4jZ9KkvjNosQ6Fz2BpsqnBTgIneiYBOMEO3cITTZrz2Nqs2aDwYhWg+DNC5L2G3XiVKmvpK/vfumDah8awLEMQ1Ss1cLa2ab6owgTe2Uw5E7WuJqSL4sPf2s9jJZ+rj3rTiyaKvPksntiUXufE4ISDEkNhW5qrQClxdiT6yhpYgJ0xju9BNXfcREHb6L/3xY/uwOpOjKJUHJneKj8YnEQ8BDZPFiwMQIo0BSnVgR0YwYSZhrBDWPDpx39jSkUgyYj8VpW19wzXVzCPd37+05gtVqKPDlorgmNvG+pR1tSswdlP8+y6wPmmej6xiohvOcU8INj6RgLUYDEZxu5a2y9EQR/dJkWPR561ZT84LtVyaUzzs6E1PbVijdAq1fphylud6YuOLHitYj67KQBU3SLJLqI0tDbYUm6mNhPG07Tw5jwTdB3f2JA9ZK6ZKKDn/5f8HLDYiIDF90gwVuFYPL4SJcRto68l/UcmmA6LzZNT1P2R7C4Ug48fsgz9RmjiAuBuSWNvVJURcNXrB6/fFE7x4RNfWIy93FoHzwFi2lJKqwsaDNRZ4QetI5hOriIuXTbj680ok6kZR7EX0r/m5+XT2J0GR5iImvAMfNfhqdx5o6TgxDq4cpjLMAba5rrA=
