dist: trusty
sudo: false
language: ruby
rvm:
- 2.5.1
env:
- JEKYLL_ENV=production
script:
- "./scripts/build.sh"
deploy:
  provider: pages
  local-dir: _site
  skip-cleanup: true
  target-branch: gh-pages
  github-token: "$GITHUB_TOKEN"
  on:
    branch: master
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: bq3ZgFj+jVsn9IxaS2k+k6g3N3o5p+yvn6zfxSpOChX30Q3Ob5SqULLylGHxr2E7oHWGfScAqBiplbf2EFH+sYW0eDuZCayGbSsX/PP+xC01ia+v53wben9hwytT7etzuBDy+BkJiRWiB6lUcpWaY1aZa0Q2TVzZKX36eFFMumBurZnqEruxHKu04HsojM9luTBxCRWn3V/R+IncVbD6yS61/YX7vCs2dQHVkShiOlGN4kpGf4bkMm3dKHHBhRxc1opbNZHniDZ2OLk5+dOZ9Wi7BhRb/LQSp17OgseqbuXkHTxYawfgOMn7fJpiCF7s+1SZtLTxMs4G+e45pDDYTpSJfmK1GKTcoF/USczqR2UoUQKVSQDytYxTjlb80D8nNdPwMeHWk09UCuaHz5KIik8lee2gXeYsra4mNAoZR5LFLORzTpSA4z0UacSy7vgHu8B4aCK4fZrH5/NGTIwOQXlV79F9T6GvsbviAQ3ms2bAZPBzxt5fSgcvpoPM72kGJEcq9b7YemAlCNXEq2nqP3I/yvn0Iy2NovPQbAepLYe35/7szxLvIemhy7qxKAOB7qHxGvUdXhqyw0ZFFR1zIFL81/dgplnV0nHtEc1vlt+BFL7sqDxkPtVTGfl1LcBzq1aooJxHShD3ZTd3Vcii6hlrMkJTjmxZB6I6Nqf//7s=
